(() => {
'use strict';const C=globalThis.ICRF,E=C.escape,I=C.icon;
const navigation=[['/','grid','研究台'],['/library','folder','论文库'],['/reader','book','双语精读'],['/search','search','科研检索'],['/graph','graph','引用网络'],['/chat','chat','研究助手'],['/jobs','clock','处理任务'],['/settings','settings','设置与数据']];
C.shell=()=>{
 document.body.innerHTML=`<a class="skip-link" href="#main" id="skip-content">跳转到主要内容</a><aside class="sidebar"><a class="brand" href="#/"><span class="brand-symbol">${I('spark')}</span><span>芯研流<small>IC RESEARCH FLOW</small></span></a><div class="sidebar-caption">你的科研工作空间</div><nav aria-label="主导航">${navigation.map(([path,icon,label])=>`<a href="#${path}" data-nav="${path}">${I(icon)}<span>${label}</span>${path==='/jobs'?'<b id="job-badge" hidden>0</b>':''}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="privacy-card">${I('shield')}<strong>${C.session.public?'私有服务器工作台':'浏览器科研工作台'}</strong><p>${C.session.public?'PDF 保存在你部署的服务器。只有授权后才发送正文给模型。':'论文保存在此浏览器。AI 请求仅在授权后直连你填写的接口。'}</p></div><small>PARALLEL STUDIO · ${E(C.session.version||'3.1.0')}</small></div></aside><div class="app"><header class="topbar"><button class="icon-btn mobile-menu" id="mobile-menu" aria-label="打开导航">${I('menu')}</button><div class="breadcrumb" id="breadcrumb">工作空间 <span>/</span> 研究台</div><form class="global-search" id="global-search">${I('search')}<input aria-label="全局检索论文" placeholder="搜索论文、术语或研究问题…"><kbd>⌘ / Ctrl K</kbd></form><button class="icon-btn" id="theme" aria-label="切换浅色和夜间主题">${I('sun')}</button><a class="profile-avatar" href="#/settings" aria-label="设置">研</a></header><main id="main" tabindex="-1"></main><footer class="app-footer"><span>原文是依据，AI 是助手。</span><span>本地索引 · 可追溯解释 · 可恢复任务</span></footer></div><div id="toasts" aria-live="polite"></div><dialog id="dialog"></dialog>`;
 C.$('#skip-content').onclick=e=>{e.preventDefault();C.$('#main').focus()};C.$('#theme').onclick=C.toggleTheme;C.$('#mobile-menu').onclick=()=>document.body.classList.toggle('nav-open');
 C.$('#global-search').onsubmit=e=>{e.preventDefault();C.go('/search?q='+encodeURIComponent(C.$('input',e.currentTarget).value))};
 if(C.shortcutHandler)document.removeEventListener('keydown',C.shortcutHandler);
 C.shortcutHandler=e=>{
  if(e.isComposing||e.keyCode===229||typeof e.key!=='string')return;
  if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){const input=C.$('#global-search input');if(input){e.preventDefault();input.focus()}}
  if(e.key==='Escape')document.body.classList.remove('nav-open','focus-reading');
 };
 document.addEventListener('keydown',C.shortcutHandler);
};
C.refresh=async()=>{C.state.papers=(await C.api('/api/papers')).papers;C.state.jobs=(await C.api('/api/jobs')).jobs;C.updateBadge()};
C.updateBadge=()=>{const count=C.state.jobs.filter(j=>['running','queued'].includes(j.status)).length;const b=C.$('#job-badge');if(b){b.hidden=!count;b.textContent=count}};
C.paperCard=p=>`<article class="paper-card"><a class="paper-thumb" href="#/reader/${p.id}"><img data-resource="/api/papers/${p.id}/thumbnail" alt="${E(p.title)} 的第一页" loading="lazy"><span class="pdf-pill">PDF · ${p.pages} 页</span>${p.translated?'<span class="translation-pill">已生成译文</span>':''}</a><div class="paper-card-body"><p class="paper-kicker">${p.year||'年份待补充'} <span>·</span> ${E(p.tags[0]||'未分类')}</p><a href="#/reader/${p.id}" class="paper-card-title">${E(p.title)}</a><p class="paper-authors">${E(p.authors.join(', ')||p.filename)}</p><div class="paper-card-footer"><a href="#/reader/${p.id}">进入精读 ${I('arrow')}</a><button class="icon-btn" data-action="paper-menu" data-id="${p.id}" aria-label="${E(p.title)} 的操作">${I('settings')}</button></div></div></article>`;
C.dashboard=()=>{
 const ps=C.state.papers,active=C.state.jobs.filter(j=>['running','queued'].includes(j.status));const root=C.$('#main');root.className='page dashboard';
 root.innerHTML=`<section class="hero"><div class="hero-copy"><p class="eyebrow"><span></span> YOUR RESEARCH, IN FOCUS</p><h1>读懂一篇论文，<br>连接<span>下一次突破。</span></h1><p class="hero-description">从原文到理解，从单篇到知识网络。让双语对照、上下文解释与可追溯的研究线索，在同一个工作台流动。</p><div class="hero-actions">${C.button('导入论文','import','primary','upload')}<a class="btn text" href="#/reader">继续阅读 ${I('arrow')}</a></div><p class="hero-privacy">${I('shield')} 无需 API Key，即可导入、阅读、批注和本地检索</p></div><div class="hero-art" aria-hidden="true"><div class="art-orbit one"></div><div class="art-orbit two"></div><div class="art-paper back"><span>原文 / SOURCE</span><i></i><i></i><i></i><div class="art-circuit">SRAM</div><i></i></div><div class="art-paper front"><span>理解 / INSIGHT</span><b>知识的连接，<br>始于一个问题。</b><i></i><i></i><div class="art-note">原文与解释，并肩而行</div><i></i></div><div class="art-spark">${I('spark')}</div></div></section><section class="metrics" aria-label="论文库统计"><div>${I('book')}<span><b>${ps.length}</b> 篇论文</span><small>你的研究积累</small></div><div>${I('file')}<span><b>${ps.reduce((a,p)=>a+p.pages,0)}</b> 页原文</span><small>可定位的原始资料</small></div><div>${I('link')}<span><b>${ps.filter(p=>p.translated).length}</b> 份译文</span><small>已生成译文 PDF</small></div><div>${I('clock')}<span><b>${active.length}</b> 个任务</span><small>正在处理或排队</small></div></section><section class="section-heading"><div><p class="eyebrow">CONTINUE YOUR EXPLORATION</p><h2>${ps.length?'回到你的阅读现场':'搭建你的第一张阅读桌'}</h2></div><a href="#/library">全部论文 ${I('arrow')}</a></section>${ps.length?`<div class="paper-grid">${ps.slice(0,3).map(C.paperCard).join('')}</div>`:`<div class="onboarding-cards"><article><b>01</b>${I('upload')}<h3>从一份 PDF 开始</h3><p>导入真实论文，原件始终保留。重复文件不会重复入库。</p></article><article><b>02</b>${I('link')}<h3>让原文与译文对话</h3><p>核对文字层后生成中文重排 PDF，点击段落定位原文，停止后可以接着翻译。</p></article><article><b>03</b>${I('spark')}<h3>将理解留在纸边</h3><p>选词解释、手写圈注和个人笔记，与来源页码一起保存。</p></article></div>`}<section class="workspace-note">${I('shield')}<div><strong>你的数据，有清晰的去向。</strong><p>${C.session.public?'原始文件和研究数据保存在当前私有服务器。模型请求会经服务器转发，请只部署到你信任的环境。':'原始文件、笔记与译文保存在当前浏览器。清除站点数据会删除论文库，请定期导出项目备份；AI 需要另行授权。'}</p></div><a href="#/settings">查看设置 ${I('arrow')}</a></section>`;
 C.bind(root,{import:C.importDialog,'paper-menu':(_,el)=>C.paperMenu(el.dataset.id)});
};
C.library=()=>{
 const root=C.$('#main');root.className='page';
 root.innerHTML=`<header class="page-heading"><div><p class="eyebrow">LIBRARY / 论文库</p><h1>每一篇，都是一条线索。</h1><p>原文、译文与阅读记录，在这里有序沉淀。</p></div>${C.button('导入论文','import','primary','upload')}</header><div class="filter-bar"><label class="search-field">${I('search')}<input id="library-query" type="search" placeholder="搜索标题、作者、标签…" aria-label="筛选论文"></label><select id="library-status" aria-label="译文状态"><option value="all">全部论文</option><option value="translated">已有译文 PDF</option><option value="pending">待翻译 / 待重排</option></select><span id="library-count"></span></div><div class="paper-grid" id="library-grid"></div>`;
 const update=()=>{const q=C.$('#library-query').value.trim().toLowerCase(),status=C.$('#library-status').value;const shown=C.state.papers.filter(p=>(`${p.title} ${p.authors.join(' ')} ${p.tags.join(' ')}`.toLowerCase().includes(q))&&(status==='all'||Boolean(p.translated)===(status==='translated')));C.$('#library-count').textContent=`${shown.length} 篇`;
 C.$('#library-grid').innerHTML=shown.length?shown.map(C.paperCard).join(''):C.empty('没有匹配的论文',C.state.papers.length?'换一个检索词，或放宽筛选条件。':'导入第一份 PDF，即可开始阅读。',C.button('导入 PDF','import','primary','upload'));C.bind(root,{import:C.importDialog,'paper-menu':(_,el)=>C.paperMenu(el.dataset.id)})};
 C.$('#library-query').oninput=update;C.$('#library-status').onchange=update;update();
};
C.paperMenu=id=>{const p=C.state.papers.find(p=>p.id===id);if(!p)return;C.modal('论文操作',`<p class="muted">${E(p.title)}</p><div class="menu-actions"><a class="btn primary" href="#/reader/${id}" id="open-reader">${I('book')}进入精读</a>${C.button('整篇翻译 / 继续翻译','translate','secondary','link')}${C.button('编辑元数据','metadata','secondary','pen')}<a class="btn secondary" href="/api/papers/${id}/project" download>${I('download')}导出项目备份</a><a class="btn secondary" href="/api/papers/${id}/original" download>${I('file')}下载原始 PDF</a>${C.button('删除论文','delete','danger','trash')}</div>`,d=>{C.$('#open-reader',d).onclick=()=>d.close();C.bind(d,{translate:()=>C.translationDialog(id),metadata:()=>C.metadataDialog(id),delete:async()=>{d.close();if(await C.confirm('删除论文与关联资料？','原件、译文、笔记和缓存会从当前浏览器删除。此操作不能撤销，请先导出项目备份。')){await C.api('/api/papers/'+id,{method:'DELETE'});await C.refresh();C.toast('论文已删除');C.render()}}})})};
C.metadataDialog=async id=>{const p=await C.api('/api/papers/'+id);C.modal('编辑论文信息',`<form id="metadata-form"><label>标题<input name="title" required maxlength="500" value="${E(p.title)}"></label><label>作者（英文逗号分隔）<input name="authors" value="${E(p.authors.join(', '))}"></label><div class="form-row"><label>年份<input name="year" type="number" min="1500" max="2200" value="${p.year||''}"></label><label>DOI<input name="doi" maxlength="300" value="${E(p.doi)}"></label></div><label>标签（英文逗号分隔）<input name="tags" value="${E(p.tags.join(', '))}"></label><p class="muted">元数据参与筛选与引用匹配。自动匹配候选不等于已经核实的引用关系。</p><button class="btn primary">保存信息</button></form>`,d=>{C.$('form',d).onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await C.api('/api/papers/'+id,{method:'PUT',body:{title:f.get('title'),authors:f.get('authors').split(',').map(x=>x.trim()).filter(Boolean),year:f.get('year')?Number(f.get('year')):null,doi:f.get('doi'),tags:f.get('tags').split(',').map(x=>x.trim()).filter(Boolean),revision:p.revision}});d.close();await C.refresh();C.toast('论文信息已保存');C.render()}catch(e){C.error(e)}}})};
C.importDialog=(retryJob=null)=>{const retry=retryJob&&['import','restore'].includes(retryJob.kind)?retryJob:null;return C.modal('把论文带到阅读桌',`${retry?`<p class="notice warning">请重新选择 ${E(retry.spec?.filename||'原文件')}。旧版本在导入失败后会清理临时副本，无法从旧任务直接恢复。你电脑上的源文件未被本站删除；已成功入库的相同 PDF 会自动去重。</p>`:''}<form id="import-form"><label class="dropzone" id="dropzone">${I('upload')}<strong>选择或拖入 PDF / 芯研流项目 ZIP</strong><span>支持批量 PDF · 单文件最多 ${C.session.limits.fileMB} MB · 最多 ${C.session.limits.pages} 页</span><input id="import-files" type="file" accept=".pdf,.zip,application/pdf,application/zip" multiple required></label><div id="file-summary" class="muted"></div><label>PDF 密码（仅加密 PDF 需要）<input id="pdf-password" type="password" autocomplete="off" placeholder="密码不写入数据库或日志"></label><p class="notice">${C.session.public?'文件将上传到你部署的私有服务器。':'文件将在当前浏览器中解析并保存。'}原始 PDF 不被改写；加密文稿的密码仅在当前页面内存中使用。此操作不调用 AI。</p><label class="check"><input type="checkbox" id="upload-consent" required>我确认在当前浏览器保存和处理这些文件。</label><button class="btn primary" id="import-submit">${I('upload')}导入并解析</button></form>`,d=>{
 const input=C.$('#import-files',d),drop=C.$('#dropzone',d);input.onchange=()=>C.$('#file-summary',d).textContent=[...input.files].map(f=>f.name).join(' · ');drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');input.files=e.dataTransfer.files;input.onchange()};
 C.$('form',d).onsubmit=async e=>{e.preventDefault();const button=C.$('#import-submit',d);button.disabled=true;let accepted=0;try{for(const file of input.files){if(!/\.(pdf|zip)$/i.test(file.name))throw new Error('请选择 PDF 或芯研流 ZIP 项目包。');const data=new FormData();data.append('file',file);data.append('password',C.$('#pdf-password',d).value);data.append('consent','true');const res=await C.api(file.name.toLowerCase().endsWith('.zip')?'/api/projects/import':'/api/papers/import',{method:'POST',body:data});accepted++;C.toast(res.duplicate?`${file.name} 已在论文库中，已跳过重复文件。`:`${file.name} 已加入解析队列。`)}d.close();await C.refresh();C.go('/jobs')}catch(err){C.error(err);if(accepted)C.toast(`已有 ${accepted} 个文件被接受；其余可单独重试。`)}finally{button.disabled=false}}
})};
C.jobsView=()=>{const root=C.$('#main');root.className='page';root.innerHTML=`<header class="page-heading"><div><p class="eyebrow">PROCESSING / 真实任务进度</p><h1>每一步，都有迹可循。</h1><p>阶段进度来自已完成的页面与段落。模型等待只显示已用时间，不编造剩余时间。</p></div>${C.button('刷新任务','refresh','secondary','restore')}</header><div id="jobs-list"></div>`;C.bind(root,{refresh:async()=>{C.state.jobs=(await C.api('/api/jobs')).jobs;C.paintJobs()}});C.paintJobs()};
C.paintJobs=()=>{
 const list=C.$('#jobs-list');if(!list)return;const statuses={running:'处理中',queued:'排队中',completed:'已完成',failed:'处理失败',cancelled:'已停止',interrupted:'已中断'};
 list.innerHTML=C.state.jobs.length?C.state.jobs.map(j=>{const active=['running','queued'].includes(j.status),p=C.state.papers.find(p=>p.id===j.paper_id);return `<article class="job-card ${j.status}"><header><div class="job-icon">${I(j.kind==='import'?'upload':j.kind==='translate'?'link':'file')}</div><div><h3>${E(p?.title||j.spec.filename||'论文处理任务')}</h3><span>${E(j.stage)} · ${C.time(j.created)}</span></div><span class="status ${j.status}">${!active&&j.status!=='completed'&&['import','restore'].includes(j.kind)?(p?'历史记录 · 原文已另次入库':'需重新选择文件'):statuses[j.status]||E(j.status)}</span></header><div class="job-progress">${active?j.total>0?`<progress value="${j.done}" max="${j.total}" aria-label="当前阶段进度"></progress><span>本阶段 ${j.done} / ${j.total}</span>`:`<progress aria-label="正在等待"></progress><span>正在等待</span>`:j.status==='completed'?'<progress value="1" max="1" aria-label="处理完成"></progress>':''}</div><p>${E(j.message||'等待可用处理资源…')}</p>${!active&&j.status!=='completed'&&['import','restore'].includes(j.kind)?(p?'<p class="muted">原文已通过另一次导入进入论文库，可直接打开阅读。本条保留该次尝试的失败记录，不代表当前仍失败。</p>':'<p class="muted">这是该次尝试的历史记录，不会在更新后自动变为成功。请重新选择文件导入；原文件和已完成数据保持不变。</p>'):''}<footer><small>${active?'已用 '+C.elapsed(j.created):'更新于 '+C.time(j.updated)}${j.usage.total_tokens?' · '+j.usage.total_tokens.toLocaleString()+' tokens':''}</small><div>${active?`<button class="btn danger small" data-action="cancel-job" data-id="${j.id}">${I('stop')}停止</button>`:''}${p?`<a class="btn secondary small" href="#/reader/${p.id}">打开论文 ${I('arrow')}</a>`:''}${!p&&!active&&j.status!=='completed'&&['import','restore'].includes(j.kind)?`<button class="btn primary small" data-action="reimport-job" data-id="${j.id}">${I('upload')}重新选择${j.kind==='restore'?'项目包':'PDF'}导入</button>`:''}${p&&!active&&j.status!=='completed'&&j.kind==='translate'?`<button class="btn primary small" data-action="resume-job" data-id="${j.id}">继续未完成部分</button>`:''}</div></footer></article>`}).join(''):C.empty('还没有处理任务','导入 PDF 或开始整篇翻译后，真实进度会显示在这里。',C.button('导入 PDF','import','primary','upload'));
 C.bind(list,{import:C.importDialog,'reimport-job':(_,el)=>C.importDialog(C.state.jobs.find(j=>j.id===el.dataset.id)),'cancel-job':async(_,el)=>{await C.api('/api/jobs/'+el.dataset.id+'/cancel',{method:'POST'});await C.refresh();C.paintJobs()},'resume-job':(_,el)=>{const j=C.state.jobs.find(j=>j.id===el.dataset.id);C.translationDialog(j.paper_id,j.spec)}});
};
C.translationDialog=async(id,restoreSpec=null)=>{const p=await C.api('/api/papers/'+id),profile=C.profile(),saved=restoreSpec||p.output?.profile||C.read('icrf.v3.translation',{}),glossary=Object.entries(saved.glossary||{}).map(([k,v])=>k+' = '+v).join('\n');const scanned=p.manifest.pages.filter(pg=>pg.scanned).length;
 C.modal('整篇翻译与中文重排',`<form id="translation-form"><p class="dialog-paper-title">${E(p.title)}</p><div class="translation-steps"><span>01 版式与保护区域</span><span>02 分批翻译与缓存</span><span>03 重排与段落对齐</span></div>${scanned?`<p class="notice warning">有 ${scanned} 页缺少可用文字层。请先补全并检查文字层。浏览器版可先用 OCR 工具生成文字层后导入，或在版式检查中补充原文。</p>`:''}<label>目标语言<select id="target-language"><option value="zh-CN">简体中文</option><option value="zh-TW">繁体中文</option><option value="en">English</option></select></label><label>术语表（每行：英文 = 译法，可留空）<textarea id="glossary" rows="5" placeholder="SRAM = 静态随机存取存储器\nthroughput = 吞吐量">${E(glossary)}</textarea></label><div class="provider-card">${I('shield')}<div><strong>接收服务：${E(profile.base_url)}</strong><p>模型：${E(profile.model||'尚未配置')} · 从浏览器直连接口（需支持 CORS）</p><a href="#/settings" id="change-model">修改模型与 API Key</a></div></div><label class="check"><input id="layout-checked" type="checkbox" required>我已检查原文顺序、图表与公式保护区域。</label><label class="check"><input id="translation-consent" type="checkbox" required>同意发送本篇待翻译正文与术语表，并承担模型费用。</label><p class="muted">源文、模型及翻译设置匹配的缓存会复用；缺失正文才会请求模型并计费，人工编辑不会自动覆盖。更换模型、目标语言或术语表会使用新缓存键。失败不会删除已完成段落，也不会自动反复请求计费。</p><div class="dialog-actions">${C.button('检查版式','layout','secondary','box')}<button class="btn primary" id="start-translation" ${scanned?'disabled':''}>${I('link')}开始 / 继续翻译</button></div></form>`,d=>{
 C.$('#target-language',d).value=saved.target||'zh-CN';C.$('#change-model',d).onclick=()=>d.close();C.bind(d,{layout:()=>{d.close();C.go('/reader/'+id+'?layout=1')},ocr:async()=>{await C.api('/api/papers/'+id+'/ocr',{method:'POST'});d.close();await C.refresh();C.go('/jobs')}});
 C.$('form',d).onsubmit=async e=>{e.preventDefault();const btn=C.$('#start-translation',d);btn.disabled=true;try{const terms={};for(const line of C.$('#glossary',d).value.split('\n').filter(s=>s.trim())){const i=line.indexOf('=');if(i<1)throw new Error('术语表每行需要使用“英文 = 中文”格式。');terms[line.slice(0,i).trim()]=line.slice(i+1).trim()}const current=C.profile();const spec={profile:current,target:C.$('#target-language',d).value,glossary:terms,consent:true};await C.api('/api/papers/'+id+'/translate',{method:'POST',body:spec});C.write('icrf.v3.translation',{target:spec.target,glossary:terms});d.close();await C.refresh();C.go('/jobs')}catch(e){C.error(e)}finally{btn.disabled=false}}
 });
};
C.settings=()=>{const root=C.$('#main'),profile=C.profile();root.className='page';root.innerHTML=`<header class="page-heading"><div><p class="eyebrow">SETTINGS / 连接、外观与数据</p><h1>按你的方式，专注研究。</h1><p>普通阅读不依赖 AI。只有明确发起请求时，论文片段或正文才会被发送。</p></div></header><div class="settings-grid"><section class="settings-card"><h2>${I('spark')}模型连接</h2><form id="settings-form"><label>OpenAI-compatible API 基础地址<input name="base_url" type="url" required value="${E(profile.base_url)}" placeholder="https://api.deepseek.com"></label><p class="field-note">接口须支持 HTTPS，并允许当前站点的跨域（CORS）请求。请仅填写你信任的服务地址。</p><label>API Key<div class="password-field"><input name="api_key" type="password" autocomplete="off" value="${E(profile.api_key)}"><button type="button" class="icon-btn" id="show-key" aria-label="显示或隐藏 API Key">${I('shield')}</button></div></label><label class="check"><input name="persist" type="checkbox" ${C.read('icrf.v3.key','')?'checked':''}>在当前浏览器持久保存 Key（共享设备不建议）</label><label>模型 ID<input name="model" list="model-options" value="${E(profile.model)}" placeholder="先获取账户模型，或手动填写"><datalist id="model-options"></datalist></label><div class="form-actions"><button class="btn primary">保存设置</button><button class="btn secondary" type="button" id="models">获取可用模型</button><button class="btn text danger-text" type="button" id="clear-key">清除 Key</button></div><p id="connection-result" role="status" class="muted">Key 不写入论文数据库、项目备份或 URL。请求从浏览器直接发送给你配置的模型服务。</p></form></section><section class="settings-card"><h2>${I('sun')}阅读氛围</h2><label>界面主题<select id="theme-select"><option value="light">纸感浅色</option><option value="dark">深色工作台（PDF 保持原色）</option></select></label><label class="check"><input type="checkbox" id="motion" ${C.read('icrf.v3.motion',true)?'checked':''}>启用界面微动效</label><label class="check"><input type="checkbox" id="intro" ${C.read('icrf.v3.intro',true)?'checked':''}>首次进入时播放欢迎动画</label><button class="btn secondary" id="replay">${I('restore')}重播入场动画</button><p class="muted">欢迎动画可跳过。系统开启“减少动态效果”时，不自动播放；论文深链接不会被打断。</p><hr><h2>${I('shield')}数据与部署</h2><p class="version-info">当前网页版本：<strong>${E(C.session.version)}</strong>。更新后若仍显示旧版，请刷新网页。</p><p>${C.session.public?'这是公开部署的私有工作台，文件和数据库位于服务器。请由管理员定期备份 data 目录。':'这是纯静态浏览器版。论文原件、缓存和笔记位于当前浏览器的 IndexedDB；清除站点数据会删除它们。设备、浏览器和网站域名之间的数据不会自动同步。'}</p><p>建议在论文操作菜单中导出项目 ZIP。项目包不包含 API Key；仅备份与当前原文匹配的译文缓存。旧缓存失效项不会使恢复中止。带批注 PDF 与原始 PDF 分开导出。</p>${C.button('导入项目备份','import','secondary','upload')}<button class="btn secondary" id="legacy">迁移当前域名的旧版论文库</button><p class="muted">此入口仅复制旧版 PDF；旧笔记请另行导出归档。不清空旧数据库，不读取旧 API Key。不同域名之间不能直接读取浏览器数据，需先在旧站点导出。</p>${C.session.requiresPassword?'<button class="btn text" id="logout">退出登录</button>':''}</section></div>`;
 const form=C.$('#settings-form');C.$('#theme-select').value=document.documentElement.dataset.theme;C.$('#theme-select').onchange=e=>{C.write('icrf.v3.theme',e.target.value);C.theme()};C.$('#motion').onchange=e=>{C.write('icrf.v3.motion',e.target.checked);C.theme()};C.$('#intro').onchange=e=>C.write('icrf.v3.intro',e.target.checked);C.$('#replay').onclick=()=>C.intro(true);
 C.$('#show-key').onclick=()=>{const e=form.elements.api_key;e.type=e.type==='password'?'text':'password'};
 form.onsubmit=e=>{e.preventDefault();const p={base_url:form.elements.base_url.value.trim(),model:form.elements.model.value.trim()},key=form.elements.api_key.value.trim();try{C.validateProfile({...p,api_key:key},{requireKey:false,requireModel:false});if(!C.write('icrf.v3.profile',p)||!C.write('icrf.v3.key',key,'session'))throw new Error('浏览器阻止保存设置，请允许本站存储。');if(form.elements.persist.checked)C.write('icrf.v3.key',key);else C.remove('icrf.v3.key');C.toast(C.volatileStorage?'浏览器存储不可用：设置仅保留在本页面内，刷新后需重新输入。':'连接设置已保存；选词解释需要重新确认外发。')}catch(e){C.error(e)}};
 C.$('#clear-key').onclick=()=>{try{C.remove('icrf.v3.key');C.remove('icrf.v3.key','session')}catch{}form.elements.api_key.value='';C.toast('当前浏览器的 Key 已清除。已发出的任务不因此撤销。')};
 C.$('#models').onclick=async e=>{e.currentTarget.disabled=true;C.$('#connection-result').textContent='正在读取账户可用模型…';try{const result=await C.api('/api/models',{method:'POST',body:{base_url:form.elements.base_url.value.trim(),model:form.elements.model.value.trim(),api_key:form.elements.api_key.value.trim()}});C.$('#model-options').innerHTML=result.models.map(m=>`<option value="${E(m)}"></option>`).join('');C.$('#connection-result').textContent=`连接成功，返回 ${result.models.length} 个模型。请明确选择支持聊天的模型并保存；列表中不一定每个模型都支持聊天。`}catch(err){C.$('#connection-result').textContent=C.errorText(err)}finally{C.$('#models').disabled=false}};
 C.bind(root,{import:C.importDialog});C.$('#legacy').onclick=()=>C.legacyImport();if(C.$('#logout'))C.$('#logout').onclick=async()=>{await C.api('/api/logout',{method:'POST'});location.reload()};
};
C.legacyImport=async()=>{try{if(!indexedDB.databases)throw new Error('浏览器不支持列出旧数据库；请使用旧站点导出脚本。');const names=(await indexedDB.databases()).map(x=>x.name);if(!names.includes('ic-research-flow'))throw new Error('当前域名没有找到旧版论文库。不同域名的数据需先在旧站点导出。');if(!await C.confirm('复制旧版论文库？','将当前域名旧 IndexedDB 中的 PDF 复制到新版浏览器论文库，不删除旧数据，也不读取 API Key。'))return;const old=await new Promise((res,rej)=>{const r=indexedDB.open('ic-research-flow');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});let papers;try{papers=await new Promise((res,rej)=>{const r=old.transaction('papers').objectStore('papers').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}finally{old.close()}let count=0;for(const p of papers){const blob=p.blob||p.pdfBlob||p.file;if(!(blob instanceof Blob))continue;const f=new FormData();f.append('file',blob,p.fileName||p.filename||'paper.pdf');f.append('consent','true');await C.api('/api/papers/import',{method:'POST',body:f});count++}C.toast(`已提交 ${count} 份原文。旧数据未删除；旧笔记请另行导出归档。`);await C.refresh();C.go('/jobs')}catch(e){C.error(e)}};
C.login=()=>{document.body.innerHTML=`<main class="login-screen"><form id="login-form"><div class="brand-symbol">${I('spark')}</div><p class="eyebrow">IC RESEARCH FLOW</p><h1>回到你的研究空间。</h1><p>这是私有科研工作台，请输入管理员设置的访问密码。</p><label>访问密码<input type="password" id="login-password" autocomplete="current-password" required autofocus></label><button class="btn primary">进入工作台 ${I('arrow')}</button><p id="login-error" role="alert"></p></form></main>`;C.$('#login-form').onsubmit=async e=>{e.preventDefault();try{await C.api('/api/login',{method:'POST',body:{password:C.$('#login-password').value}});await C.start()}catch(e){C.$('#login-error').textContent=e.message}}};
C.render=async()=>{const ticket=++C.state.routeVersion;C.state.reader?.destroy?.();C.state.reader=null;document.body.classList.remove('nav-open','focus-reading');const u=C.route(),route=u.pathname;const nav=navigation.find(([p])=>p==='/'?route==='/':route.startsWith(p));C.$$('.sidebar nav a').forEach(a=>{a.classList.toggle('active',a.dataset.nav===nav?.[0]);a.setAttribute('aria-current',a.dataset.nav===nav?.[0]?'page':'false')});C.$('#breadcrumb').innerHTML=`工作空间 <span>/</span> ${E(nav?.[2]||'页面未找到')}`;const root=C.$('#main');root.innerHTML='<div class="loading-state" role="status"><span class="spinner"></span>正在读取工作空间…</div>';try{await C.refresh();if(ticket!==C.state.routeVersion)return;if(route==='/')C.dashboard();else if(route==='/library'||route==='/reader')C.library();else if(route.startsWith('/reader/'))await C.reader(route.split('/')[2],u.searchParams,ticket);else if(route==='/jobs')C.jobsView();else if(route==='/settings')C.settings();else if(route==='/search')C.searchView(u.searchParams.get('q')||'');else if(route==='/graph')await C.graphView();else if(route==='/chat')C.chatView();else root.innerHTML=C.empty('这个页面不存在','回到工作空间继续阅读。','<a class="btn primary" href="#/">返回研究台</a>')}catch(e){if(ticket===C.state.routeVersion)root.innerHTML=C.empty('无法载入工作空间',e.message,C.button('重试','retry','primary','restore'));C.bind(root,{retry:C.render})}};
C.poll=async()=>{try{const before=C.state.jobs;C.state.jobs=(await C.api('/api/jobs')).jobs;C.updateBadge();if(C.route().pathname==='/jobs'&&JSON.stringify(before)!==JSON.stringify(C.state.jobs))C.paintJobs();const finished=C.state.jobs.filter(j=>j.status==='completed'&&before.some(x=>x.id===j.id&&['running','queued'].includes(x.status)));if(finished.length){C.state.papers=(await C.api('/api/papers')).papers;C.toast('任务已完成，结果已保存。');if(['/', '/library','/reader'].includes(C.route().pathname))C.render();if(C.state.reader&&finished.some(j=>j.paper_id===C.state.reader.id))C.state.reader.showReload()}}catch{}finally{C.pollTimer=setTimeout(C.poll,1600)}};
C.start=async()=>{try{C.session=await C.api('/api/session');C.theme();if(!C.session.authenticated){C.login();return}C.shell();await C.render();if(C.pollTimer)clearTimeout(C.pollTimer);C.pollTimer=setTimeout(C.poll,1600);if(C.route().pathname==='/')C.intro()}catch(e){document.body.innerHTML=`<main class="startup-error"><h1>浏览器工作空间未能打开</h1><p>${E(e.message)}</p><p>请允许本站使用浏览器存储，并通过网站地址访问。隐私模式或存储配额限制可能阻止打开。</p><button id="reconnect">重新连接</button></main>`;C.$('#reconnect').onclick=()=>location.reload()}};
window.addEventListener('hashchange',()=>{if(C.session?.authenticated)C.render()});

})();
