(() => {
'use strict';
const C=ICRF,E=C.escape,I=C.icon;
C.reader=async(id,params,ticket)=>{
 const [paper,notes]=await Promise.all([C.api('/api/papers/'+id),C.api('/api/papers/'+id+'/notes')]);
 if(ticket!==C.state.routeVersion)return;
 const root=C.$('#main');root.className='reader-workbench';
 const pos=C.read('icrf.v3.position.'+id,{});
 const R={id,paper,notes:notes.notes,sourcePage:C.clamp(params.get('page')||pos.page||1,1,paper.pages),targetPage:1,mode:params.get('view')==='parallel'?'parallel':'assistant',tool:'text',zoom:{source:1,target:1},selection:null,answer:'',conversation:[],busy:false,auto:false,consent:false,profile:C.profile(),seq:0,alive:true,images:{},controllers:{},sync:true,scrollLock:false,viewVersion:0,observers:{},latex:'',imageConsent:false,drafts:new Map()};
 C.state.reader=R;
 R.destroy=()=>{R.alive=false;R.seq++;clearTimeout(R.autoTimer);clearTimeout(R.selectTimer);clearTimeout(R.latexTimer);clearTimeout(R.scrollTimer);clearInterval(R.clock);R.abort?.abort();Object.values(R.controllers).forEach(c=>c.abort());Object.values(R.images).forEach(URL.revokeObjectURL);R.resize?.disconnect();Object.values(R.observers).forEach(o=>o.disconnect());document.removeEventListener('selectionchange',R.selectionChange);window.removeEventListener('keydown',R.keys)};
 R.showReload=()=>{const n=C.$('#reader-reload');if(n){n.hidden=false;n.onclick=()=>C.render()}};
 root.innerHTML=`<header class="reader-heading"><div><a href="#/library" class="back-link">${I('left')}论文库</a><h1 title="${E(paper.title)}">${E(paper.title)}</h1><p>${paper.pages} 页 · ${E(paper.authors.join(' / ')||'作者未填写')} ${paper.year?'· '+paper.year:''}</p></div><div class="reader-heading-actions"><button class="btn secondary" id="reader-reload" hidden>${I('restore')}结果已更新 · 重新载入</button>${C.button('整篇翻译','translate','primary','spark')}<button class="icon-btn" data-action="more" aria-label="论文操作菜单">${I('menu')}</button></div></header>
 <div class="reader-command"><div class="segmented" id="reader-modes"><button data-mode="assistant">${I('spark')}划词精读</button><button data-mode="parallel">${I('book')}双 PDF 对照</button><button data-mode="edit">${I('pen')}译文校对</button></div><div class="command-right"><button class="btn text" data-action="layout">${I('grid')}版式检查</button><button class="btn text" data-action="notes">${I('pen')}笔记 <span id="notes-count">${R.notes.length}</span></button><button class="icon-btn" data-action="focus" aria-label="切换专注阅读">${I('expand')}</button></div></div>
 <div id="reader-warning">${paper.layoutStatus?.outdated?'<div class="notice warning layout-health"><span>这篇论文使用旧版版式识别，高亮正文可能被错误保护。请先在浏览器重新识别，之后补译未翻译段落；原件和笔记保留。</span><button class="btn secondary" data-action="reanalyze">浏览器重新识别版式</button></div>':''}${paper.layoutStatus?.needsReview?'<div class="notice warning">有 '+paper.layoutStatus.issues.length+' 个内容块需要核对文字层或保护范围，请打开版式检查。</div>':''}${!paper.translated&&paper.output?'<div class="notice warning">译文或版式已修改，下方 PDF 是上一次版本；重新排版后才会更新。<button class="btn text" data-action="compose">使用缓存重新排版</button></div>':''}${paper.translation?'<div class="quality-line">'+I('shield')+'已生成译文 PDF · 结构覆盖不等于翻译完整，仍需核对版式与语义</div>':''}</div>
 <div class="reader-mobile-tabs segmented"><button data-mobile="source" class="active">原文</button><button data-mobile="right">解释 / 译文</button></div>
 <div class="reader-split" id="reader-split"><section class="pdf-pane source-pane" aria-label="论文原文"><div class="pane-label"><span><i class="source-dot"></i>原文 ORIGINAL</span><span>原始文件保持不变</span></div><div class="pdf-toolbar"><div class="page-controls"><button class="icon-btn" data-turn="source:-1" aria-label="原文上一页">${I('left')}</button><input class="page-input" id="source-page" aria-label="原文页码" type="number" min="1" max="${paper.pages}" value="${R.sourcePage}"><span>/ ${paper.pages}</span><button class="icon-btn" data-turn="source:1" aria-label="原文下一页">${I('right')}</button></div><select id="source-zoom" aria-label="原文缩放"><option value="1">适宽</option><option value="1.25">125%</option><option value="1.5">150%</option><option value="2">200%</option></select><div class="selection-tools"><button class="icon-btn active" data-tool="text" title="划词高亮" aria-label="划词高亮">${I('text')}</button><button class="icon-btn" data-tool="box" title="框选文字" aria-label="框选文字">${I('box')}</button><button class="icon-btn" data-tool="ink" title="自由手写批注" aria-label="自由手写批注">${I('pen')}</button></div></div><div class="pdf-viewport" id="source-viewport" tabindex="0"><div class="pdf-sheet" id="source-sheet"></div></div><footer class="pdf-footer" id="source-footer">选择词句，右侧解释。双击段落可定位对应译文。</footer></section>
 <div class="split-handle" id="split-handle" role="separator" aria-label="调整左右面板宽度" aria-orientation="vertical" aria-valuemin="35" aria-valuemax="75" aria-valuenow="58" tabindex="0"><span></span></div>
 <section class="reader-right" id="reader-right"></section></div>`;
 const setWidth=x=>{x=C.clamp(x,35,75);C.$('#reader-split').style.setProperty('--split',x+'%');C.$('#split-handle').setAttribute('aria-valuenow',String(Math.round(x)))};
 setWidth(C.read('icrf.v3.split',58));const handle=C.$('#split-handle');
 handle.onpointerdown=e=>{handle.setPointerCapture(e.pointerId);handle.onpointermove=e=>{const r=C.$('#reader-split').getBoundingClientRect();setWidth((e.clientX-r.left)/r.width*100)};handle.onpointerup=()=>{handle.onpointermove=null;C.write('icrf.v3.split',+handle.getAttribute('aria-valuenow'))}};
 handle.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();setWidth(e.key==='Home'?35:e.key==='End'?75:+handle.getAttribute('aria-valuenow')+(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?5:1));C.write('icrf.v3.split',+handle.getAttribute('aria-valuenow'))}};handle.ondblclick=()=>setWidth(58);
 const pageData=side=>side==='source'?R.paper.manifest.pages[R.sourcePage-1]:R.paper.translation?.pages[R.targetPage-1];
 function normalizeRect(r,pg){return [r[0]/pg.width,r[1]/pg.height,r[2]/pg.width,r[3]/pg.height].map(x=>C.clamp(x,0,1))}
 function selectionShapes(){const s=R.selection;return s&&s.page===R.sourcePage?s.rects:[]}
 R.paintMarks=()=>{const layer=C.$('#source-sheet .pdf-marks');if(!layer)return;const notes=R.notes.filter(n=>n.page===R.sourcePage);layer.innerHTML=notes.flatMap(n=>(n.rects||[]).map(r=>`<div class="pdf-mark saved ${E(n.kind)}" style="left:${r[0]*100}%;top:${r[1]*100}%;width:${(r[2]-r[0])*100}%;height:${(r[3]-r[1])*100}%"></div>`)).join('')+selectionShapes().map(r=>`<div class="pdf-mark selected" style="left:${r[0]*100}%;top:${r[1]*100}%;width:${(r[2]-r[0])*100}%;height:${(r[3]-r[1])*100}%"></div>`).join('');const inks=[...notes.filter(n=>n.kind==='ink'),...(R.selection?.kind==='ink'&&R.selection.page===R.sourcePage?[R.selection]:[])];layer.innerHTML+=`<svg class="ink-svg" viewBox="0 0 1000 1000" preserveAspectRatio="none">${inks.map(n=>`<polyline points="${n.points.map(p=>p.map(x=>x*1000).join(',')).join(' ')}" fill="none" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke"/>`).join('')}</svg>`};
 async function showPage(side,number,link=true){
  const max=side==='source'?R.paper.pages:(R.paper.translation?.pages.length||1);number=C.clamp(number,1,max);if(side==='source')R.sourcePage=number;else R.targetPage=number;
  if(side==='source'){C.$('#source-page').value=number;C.write('icrf.v3.position.'+id,{page:number});}else if(C.$('#target-page'))C.$('#target-page').value=number;
  const sheet=C.$('#'+side+'-sheet');if(!sheet)return;const pg=pageData(side);if(!pg)return;
  const version=++R.viewVersion;sheet.dataset.version=version;sheet.style.width=(100*R.zoom[side])+'%';sheet.style.aspectRatio=pg.width+'/'+pg.height;
  sheet.innerHTML='<div class="pdf-loading" role="status"><span class="spinner"></span>正在渲染真实 PDF…</div>';R.controllers[side]?.abort();const control=new AbortController();R.controllers[side]=control;
  try{
   const res=await C.fetch(`/api/papers/${id}/render/${number}?side=${side}&scale=${Math.min(3,Math.round(1.6*R.zoom[side]*10)/10)}`,{signal:control.signal,credentials:'same-origin'});
   if(!res.ok){const v=await res.json();throw new Error(v.detail||'页面渲染失败')}
   const blob=await res.blob();if(!R.alive||String(version)!==sheet.dataset.version)return;
   if(R.images[side])URL.revokeObjectURL(R.images[side]);const url=R.images[side]=URL.createObjectURL(blob);
   const blocks=new Map(pg.blocks.map(b=>[b.id,b.order]));const words=[...pg.words].sort((a,b)=>(blocks.get(a.blockId)||0)-(blocks.get(b.blockId)||0)||a.bbox[1]-b.bbox[1]||a.bbox[0]-b.bbox[0]);
   sheet.innerHTML=`<img class="pdf-page-image" src="${url}" alt="${side==='source'?'原文':'译文'}第 ${number} 页" draggable="false"><div class="word-layer" aria-label="可选择的 PDF 文字">${words.map((w,i)=>{const r=normalizeRect(w.bbox,pg);return `<span class="pdf-word" data-index="${i}" data-block="${E(w.blockId||'')}" style="left:${r[0]*100}%;top:${r[1]*100}%;width:${(r[2]-r[0])*100}%;height:${(r[3]-r[1])*100}%">${E(w.text)} </span>`}).join('')}</div><div class="pdf-marks" aria-hidden="true"></div><div class="draw-layer" aria-hidden="true"></div>`;
   sheet.words=words;sheet.pageInfo=pg;
   // Match transparent selectable glyphs to each actual PDF word box.
   R.observers[side]?.disconnect();
   let fitting=0;
   const fit=()=>{cancelAnimationFrame(fitting);fitting=requestAnimationFrame(()=>{
    if(!sheet.isConnected)return;
    const sw=sheet.clientWidth,sh=sheet.clientHeight;
    C.$$('.pdf-word',sheet).forEach(el=>{const word=words[+el.dataset.index],r=normalizeRect(word.bbox,pg),w=(r[2]-r[0])*sw,h=(r[3]-r[1])*sh;
     el.style.fontSize=(h*.85)+'px';el.style.transform='';el.style.width='auto';const natural=el.getBoundingClientRect().width;el.style.transform=`scaleX(${natural?w/natural:1})`;
    });
   })};
   R.observers[side]=new ResizeObserver(fit);R.observers[side].observe(sheet);fit();if(side==='source'){R.paintMarks();setTool(R.tool);bindDrawing();sheet.ondblclick=e=>{const w=e.target.closest('[data-block]');if(w&&R.mode==='parallel')R.align('source',w.dataset.block)}}
   else sheet.onclick=e=>{const w=e.target.closest('[data-block]');if(w){const r=w.getBoundingClientRect(),parent=sheet.getBoundingClientRect();const near=R.paper.translation.alignment.filter(a=>a.targetPage===R.targetPage).sort((a,b)=>Math.abs(a.targetRect[1]/pg.height-(r.top-parent.top)/parent.height)-Math.abs(b.targetRect[1]/pg.height-(r.top-parent.top)/parent.height))[0];if(near)R.align('target',near.blockId)}};
   if(side==='source'){C.$('#source-footer').textContent=pg.scanned?'这一页缺少文字层。请用 OCR 工具生成文字层后导入，或在版式检查中补充原文。':`${pg.columns==='double'?'检测到双栏 · 请核对阅读顺序':'可选择文字'} · ${pg.blocks.filter(b=>b.kind==='protected').length} 个图形 / 公式保护块`;if(R.mode==='edit')paintEditor();}
   if(link&&R.sync&&R.mode==='parallel'){const first=pg.blocks.find(b=>b.kind!=='ignore');if(first)R.align(side,first.id)}
  }catch(e){if(e.name!=='AbortError'&&R.alive&&String(version)===sheet.dataset.version){sheet.innerHTML=`<div class="pdf-loading error-text"><p>${E(e.message)}</p><button class="btn secondary">重试本页</button></div>`;C.$('button',sheet).onclick=()=>showPage(side,number,false)}}
 }
 function setTool(tool){R.tool=tool;C.$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));C.$('#source-sheet').dataset.tool=tool}
 function selectionKey(s){return JSON.stringify([s.page,s.quote,(s.rects||[]).map(r=>r.map(n=>Math.round(n*1000)))]);}
 function selectionRect(s){
  if(!s)return null;const rects=s.rects||[];if(!rects.length)return null;
  return [Math.min(...rects.map(r=>r[0])),Math.min(...rects.map(r=>r[1])),Math.max(...rects.map(r=>r[2])),Math.max(...rects.map(r=>r[3]))];
 }
 function cropURL(s){const r=selectionRect(s);return r?`/api/papers/${id}/crop/${s.page}?x0=${r[0]}&y0=${r[1]}&x1=${r[2]}&y1=${r[3]}`:'';}
 function setSelection(s,{saved=false}={}){
  if(R.selection)R.drafts.set(selectionKey(R.selection),{comment:R.comment||'',latex:R.latex||'',question:R.question||''});
  if(R.drafts.size>50)R.drafts.delete(R.drafts.keys().next().value);
  const draft=saved?s:(R.drafts.get(selectionKey(s))||{});R.comment=draft.comment||'';R.latex=draft.latex||'';R.question=draft.question||'';R.imageConsent=false;
  R.abort?.abort();R.seq++;clearTimeout(R.autoTimer);R.busy=false;R.selection=s;R.answer=saved?(s.answer||''):'';R.conversation=[];R.paintMarks();if(R.mode!=='assistant'){setMode('assistant');}else paintAssistant();
  if(!saved&&R.auto&&R.consent&&s.quote)R.autoTimer=setTimeout(()=>ask(),700);
 }
 R.selectionChange=()=>{if(R.tool!=='text'||!R.alive)return;clearTimeout(R.selectTimer);R.selectTimer=setTimeout(()=>{const sel=window.getSelection(),sheet=C.$('#source-sheet');if(!sel?.rangeCount||sel.isCollapsed||!sheet)return;const range=sel.getRangeAt(0);if(!sheet.contains(range.startContainer)||!sheet.contains(range.endContainer))return;const quote=sel.toString().replace(/\s+/g,' ').trim().slice(0,3000);if(!quote)return;const r=sheet.getBoundingClientRect();const rects=[...range.getClientRects()].filter(x=>x.width>0&&x.height>0).slice(0,150).map(x=>[C.clamp((x.left-r.left)/r.width,0,1),C.clamp((x.top-r.top)/r.height,0,1),C.clamp((x.right-r.left)/r.width,0,1),C.clamp((x.bottom-r.top)/r.height,0,1)]).filter(x=>x[2]>x[0]&&x[3]>x[1]);if(R.selection?.quote===quote&&R.selection?.page===R.sourcePage)return;setSelection({page:R.sourcePage,quote,rects,points:[],kind:'highlight'})},130)};
 document.addEventListener('selectionchange',R.selectionChange);
 function bindDrawing(){const layer=C.$('#source-sheet .draw-layer');layer.onpointerdown=e=>{if(R.tool==='text')return;e.preventDefault();layer.setPointerCapture(e.pointerId);const sheet=C.$('#source-sheet'),r=sheet.getBoundingClientRect(),coord=e=>[C.clamp((e.clientX-r.left)/r.width,0,1),C.clamp((e.clientY-r.top)/r.height,0,1)],start=coord(e),points=[start];let end=start;layer.onpointermove=e=>{end=coord(e);if(points.length<1500)points.push(end);if(R.tool==='box')layer.innerHTML=`<div class="drawing-box" style="left:${Math.min(start[0],end[0])*100}%;top:${Math.min(start[1],end[1])*100}%;width:${Math.abs(start[0]-end[0])*100}%;height:${Math.abs(start[1]-end[1])*100}%"></div>`;else layer.innerHTML=`<svg class="ink-svg" viewBox="0 0 1000 1000" preserveAspectRatio="none"><polyline points="${points.map(p=>p.map(x=>x*1000).join(',')).join(' ')}" fill="none" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke"/></svg>`};layer.onpointerup=()=>{layer.onpointermove=null;layer.innerHTML='';if(R.tool==='ink'){if(points.length<2)return;setSelection({page:R.sourcePage,kind:'ink',quote:'',points,rects:[]});return;}const box=[Math.min(start[0],end[0]),Math.min(start[1],end[1]),Math.max(start[0],end[0]),Math.max(start[1],end[1])];if(box[2]-box[0]<.003||box[3]-box[1]<.003)return;const pg=sheet.pageInfo;const chosen=sheet.words.filter(w=>{const b=normalizeRect(w.bbox,pg),cx=(b[0]+b[2])/2,cy=(b[1]+b[3])/2;return cx>=box[0]&&cx<=box[2]&&cy>=box[1]&&cy<=box[3]});setSelection({page:R.sourcePage,kind:'box',quote:chosen.map(w=>w.text).join(' ').slice(0,3000),points:[],rects:[box]});if(!chosen.length)C.toast('已保存图形选区；它不会被假装识别成文字。可添加自己的批注。')}}}
 async function ask(){
  if(R.busy||!R.selection||(!R.selection.quote&&!R.imageConsent))return;if(!R.consent){C.toast('请先确认当前选文将发送到配置的模型。','error');return}
  if(!R.profile.api_key||!R.profile.model){C.toast('请先在设置中配置 Key 和模型。','error');return}
  const mode=C.$('#explanation-mode')?.value||'explain',question=C.$('#selection-question')?.value||'';R.question=question;R.explanationMode=mode;R.busy=true;R.started=Date.now();const seq=++R.seq,selection=structuredClone(R.selection);R.abort?.abort();R.abort=new AbortController();paintAssistant();
  try{const res=await C.api('/api/chat',{method:'POST',signal:R.abort.signal,body:{profile:R.profile,mode,question,quote:selection.quote,paper_id:id,page:selection.page,history:R.conversation.slice(-8),consent:true,latex:R.latex||'',include_image:R.imageConsent,image_consent:R.imageConsent,selection_rect:R.imageConsent?selectionRect(selection):null}});if(!R.alive||seq!==R.seq)return;R.answer=res.text;R.model=res.model;R.usage=res.usage;R.conversation.push({role:'user',content:question||selection.quote},{role:'assistant',content:res.text});R.busy=false;paintAssistant()}catch(e){if(seq===R.seq&&R.alive){R.busy=false;paintAssistant();C.error(e)}}
 }
 function stop(){R.seq++;R.abort?.abort();clearTimeout(R.autoTimer);R.busy=false;paintAssistant()}
 function paintAssistant(){if(R.mode!=='assistant'||!R.alive)return;const target=C.$('#reader-right');target.className='reader-right assistant-pane';const s=R.selection;target.innerHTML=`<div class="pane-label"><span>${I('spark')}阅读助手</span><span class="tag">围绕当前选文</span></div><div class="assistant-scroll"><div class="assistant-intro"><div class="assistant-symbol">${I('spark')}</div><h2>读懂每一个关键细节。</h2><p>从术语到论证，与原文保持连接。</p></div>${s?`<section class="selection-card"><header><span>原文摘录</span><button class="btn text tiny" id="selection-source">第 ${s.page} 页 ${I('arrow')}</button></header><blockquote>${E(s.quote||'图形 / 手写选区，没有附带可识别文字。')}</blockquote></section>`:'<div class="selection-empty">在左侧划选一个词或句子；也可使用框选和手写批注。<span>仅选择不会调用 AI，也不会收费。</span></div>'}
 <label>解释方式<select id="explanation-mode"><option value="explain">术语与上下文解释</option><option value="translate">学术翻译</option><option value="formula">公式与物理意义</option><option value="critique">方法、假设与局限</option></select></label>
 ${R.answer?`<article class="ai-answer"><header>${I('spark')}AI 解释 <span>${E(R.model||R.profile.model)}</span></header>${C.mathHTML(R.answer)}<p class="disclaimer">AI 生成 · 补充知识不等于原文证据，请对照来源核验。</p></article>`:''}
 ${R.busy?'<div class="answer-loading" role="status"><span class="spinner"></span><strong>正在理解选文…</strong><span id="answer-time"></span><div class="indeterminate"></div><button class="btn secondary" id="stop-answer">停止等待</button><small>停止等待不保证撤销服务商计费。</small></div>':''}
 ${s?`<details class="formula-editor" ${R.latex?'open':''}><summary>公式核对 · 原图 / 手动 LaTeX</summary><p class="muted">LaTeX 排版不能恢复已丢失的上下标。请对照原图校正；下方预览在本机完成，不调用 AI。</p>${selectionRect(s)?`<img class="selection-crop" data-resource="${cropURL(s)}" alt="原文第 ${s.page} 页的真实选区裁图">`:'<p>框选公式区域后可以查看原图。</p>'}<label>校正公式（不带定界符）<textarea id="manual-latex" maxlength="8000" spellcheck="false" placeholder="例如：\\frac{a}{b} = \\sum_{i=1}^{n} x_i">${E(R.latex||'')}</textarea></label><div class="math-block"><div class="math-output" id="latex-preview"></div><small class="math-status" role="status"></small></div></details>`:''}
 <label>${R.answer?'围绕同一选区继续追问':'补充问题（可选）'}<textarea id="selection-question" rows="2" maxlength="4000" placeholder="例如：这里的假设为什么成立？">${E(R.question||'')}</textarea></label>
 <div class="consent-box"><p>${I('shield')}发送到 <strong>${E(R.profile.base_url)}</strong><br>模型：${E(R.profile.model||'尚未配置')} · 当前选文、附近文字、标题、页码、手工校正公式及同选区追问。不勾选下方图片授权则只发文字。</p><label class="check"><input id="reader-consent" type="checkbox" ${R.consent?'checked':''}>我同意发送以上内容，知道可能产生模型费用</label><label class="check"><input id="auto-explain" type="checkbox" ${R.auto?'checked':''} ${R.consent?'':'disabled'}>选词后自动解释（可随时关闭）</label></div>
 ${s&&selectionRect(s)?`<div class="image-consent"><label class="check"><input id="image-consent" type="checkbox" ${R.imageConsent?'checked':''} ${!R.consent?'disabled':''}>另同意发送当前选区矩形图片（包含矩形内全部内容）</label><small>需使用支持图片的模型；不自动换模型。此选区的每次追问都会附带图片，可能额外计费。</small></div>`:''}
 <button class="btn primary wide" id="ask-selection" ${R.busy||(!s?.quote&&!R.imageConsent)?'disabled':''}>${I('spark')}${R.answer?'发送追问':'解释选中内容'}</button>
 <section class="note-compose"><label>我的理解与批注<textarea id="note-comment" rows="3" maxlength="10000" placeholder="把自己的判断也留在这里。">${E(R.comment||'')}</textarea></label><button class="btn secondary wide" id="save-note" ${!s?'disabled':''}>${I('pen')}保存选区、解释与笔记</button></section></div>`;
 C.$('#explanation-mode').value=R.explanationMode||'explain';C.$('#explanation-mode').onchange=e=>R.explanationMode=e.target.value;C.$('#selection-question').oninput=e=>R.question=e.target.value;C.$('#note-comment').oninput=e=>R.comment=e.target.value;
 C.$('#reader-consent').onchange=e=>{R.consent=e.target.checked;if(!R.consent){R.auto=false;R.imageConsent=false;stop()}else{C.$('#auto-explain').disabled=false;if(C.$('#image-consent'))C.$('#image-consent').disabled=false}};
 C.$('#auto-explain').onchange=e=>{R.auto=e.target.checked;clearTimeout(R.autoTimer)};C.$('#ask-selection').onclick=ask;if(C.$('#stop-answer'))C.$('#stop-answer').onclick=stop;
 C.mathEnhance(target);
 if(C.$('#manual-latex')){const preview=C.$('#latex-preview');const update=()=>C.mathRender(preview,R.latex?'\\['+R.latex+'\\]':'在上方输入 LaTeX 后预览。');update();C.$('#manual-latex').oninput=e=>{R.latex=e.target.value;clearTimeout(R.latexTimer);R.latexTimer=setTimeout(update,250)};}
 if(C.$('#image-consent'))C.$('#image-consent').onchange=e=>{R.imageConsent=e.target.checked;C.$('#ask-selection').disabled=R.busy||(!s?.quote&&!R.imageConsent)};
 if(C.$('#selection-source'))C.$('#selection-source').onclick=()=>showPage('source',s.page,false);
 C.$('#save-note').onclick=async e=>{e.currentTarget.disabled=true;try{await C.api('/api/papers/'+id+'/notes',{method:'POST',body:{page:s.page,quote:s.quote,rects:s.rects,points:s.points,kind:s.kind,answer:R.answer,comment:R.comment||'',model:R.model||'',latex:R.latex||''}});R.notes=(await C.api('/api/papers/'+id+'/notes')).notes;if(!R.alive)return;C.$('#notes-count').textContent=R.notes.length;R.comment='';R.paintMarks();C.toast('笔记已保存到论文，不会再次调用 AI。');paintAssistant()}catch(e){if(!R.alive)return;C.error(e);C.$('#save-note').disabled=false}};
 clearInterval(R.clock);if(R.busy)R.clock=setInterval(()=>{const n=C.$('#answer-time');if(n)n.textContent='已用 '+Math.floor((Date.now()-R.started)/1000)+' 秒'},1000);
 }
 function paintParallel(){const target=C.$('#reader-right');target.className='reader-right pdf-pane target-pane';if(!R.paper.translation){target.innerHTML=C.empty('把全文，也读懂。','完成整篇翻译后，这里会显示真正的中文 PDF，支持段落定位、同步与独立翻页。',C.button('翻译整篇论文','translate','primary','spark'));C.bind(target,{translate:()=>C.translationDialog(id)});return}
 const n=R.paper.translation.pages.length;target.innerHTML=`<div class="pane-label"><span><i class="target-dot"></i>译文 TRANSLATION</span><a href="/api/papers/${id}/translated" class="btn text tiny">${I('download')}PDF</a></div><div class="pdf-toolbar"><div class="page-controls"><button class="icon-btn" data-turn="target:-1" aria-label="译文上一页">${I('left')}</button><input type="number" class="page-input" id="target-page" min="1" max="${n}" value="${R.targetPage}" aria-label="译文页码"><span>/ ${n}</span><button class="icon-btn" data-turn="target:1" aria-label="译文下一页">${I('right')}</button></div><select id="target-zoom" aria-label="译文缩放"><option value="1">适宽</option><option value="1.25">125%</option><option value="1.5">150%</option><option value="2">200%</option></select><label class="check sync-control"><input id="sync-pages" type="checkbox" ${R.sync?'checked':''}>段落同步</label></div><div class="pdf-viewport" id="target-viewport" tabindex="0"><div class="pdf-sheet" id="target-sheet"></div></div><footer class="pdf-footer">中文单栏重排 · 附原页核对图，保留图表与公式 · 点击译文定位原页</footer>`;
 C.$('#target-page').onchange=e=>showPage('target',+e.target.value,false);C.$('#target-zoom').value=R.zoom.target;C.$('#target-zoom').onchange=e=>{R.zoom.target=+e.target.value;showPage('target',R.targetPage,false)};C.$('#sync-pages').onchange=e=>R.sync=e.target.checked;bindTurns(target);bindScroll('target');showPage('target',R.targetPage,false);
 }
 R.align=async(side,blockId)=>{if(!R.paper.translation||R.mode!=='parallel'||R.scrollLock)return;const map=R.paper.translation.alignment;let a=map.find(a=>a.blockId===blockId&&(side==='source'?a.sourcePage:a.targetPage)===(side==='source'?R.sourcePage:R.targetPage));if(!a)return;const other=side==='source'?'target':'source',number=other==='source'?a.sourcePage:a.targetPage;R.scrollLock=true;try{if((other==='source'?R.sourcePage:R.targetPage)!==number)await showPage(other,number,false);const pg=pageData(other),sheet=C.$('#'+other+'-sheet'),vp=C.$('#'+other+'-viewport'),rect=other==='source'?a.sourceRect:a.targetRect;if(sheet&&vp){const y=rect[1]/pg.height*sheet.getBoundingClientRect().height;vp.scrollTop=Math.max(0,sheet.offsetTop+y-vp.clientHeight*.25);const marks=C.$('.pdf-marks',sheet);if(marks){const n=document.createElement('div'),r=normalizeRect(rect,pg);n.className='alignment-flash';n.style.cssText=`left:${r[0]*100}%;top:${r[1]*100}%;width:${(r[2]-r[0])*100}%;height:${(r[3]-r[1])*100}%`;marks.append(n);setTimeout(()=>n.remove(),1600)}}}finally{setTimeout(()=>R.scrollLock=false,150)}};
 function bindScroll(side){const vp=C.$('#'+side+'-viewport');if(!vp)return;vp.onscroll=()=>{if(R.mode!=='parallel'||!R.sync||R.scrollLock)return;clearTimeout(R.scrollTimer);R.scrollTimer=setTimeout(()=>{const sheet=C.$('#'+side+'-sheet'),pg=pageData(side);if(!sheet||!pg)return;const ratio=(vp.scrollTop+vp.clientHeight*.3-sheet.offsetTop)/sheet.getBoundingClientRect().height;const a=R.paper.translation.alignment.filter(a=>(side==='source'?a.sourcePage:a.targetPage)===(side==='source'?R.sourcePage:R.targetPage)).sort((a,b)=>Math.abs((side==='source'?a.sourceRect:a.targetRect)[1]/pg.height-ratio)-Math.abs((side==='source'?b.sourceRect:b.targetRect)[1]/pg.height-ratio))[0];if(a)R.align(side,a.blockId)},100)}}
 async function paintEditor(){const target=C.$('#reader-right');target.className='reader-right editor-pane';target.innerHTML='<div class="loading-state">正在载入真实译文缓存…</div>';const result=await C.api('/api/papers/'+id+'/translations');if(R.mode!=='edit'||!R.alive)return;const pg=pageData('source');const rows=result.translations;R.translationRows=rows;
 target.innerHTML=`<div class="pane-label"><span>${I('pen')}逐段校对 · 原文第 ${R.sourcePage} 页</span></div><div class="editor-scroll"><p class="muted">修改只更新译文缓存，不会请求 AI。校对后点击“重新排版”，再查看完整 PDF。</p>${pg.blocks.filter(b=>b.kind==='text').map(b=>{const candidates=rows.filter(r=>r.block_id===b.id&&r.source_hash===b.sourceHash),r=candidates.find(r=>JSON.stringify(r.profile)===JSON.stringify(R.paper.output?.profile))||candidates[0];return `<article class="translation-editor" data-block="${E(b.id)}"><details><summary>查看原文 · 段 ${b.order+1}</summary><p>${E(b.text)}</p></details>${r?`<small>${E(r.profile.profile.model)} · ${E(r.profile.target)} ${r.edited?'· 已人工编辑':''}</small><textarea data-cache="${E(r.cache_key)}" rows="6" maxlength="30000">${E(r.target)}</textarea><button class="btn secondary" data-save="${E(r.cache_key)}">保存本段修改</button>`:'<p class="notice">还没有这个段落的匹配译文，请先整篇翻译。</p>'}</article>`}).join('')}${!pg.blocks.some(b=>b.kind==='text')?'<p>本页没有需要翻译的正文块。</p>':''}<div class="editor-bottom">${C.button('使用缓存重新排版','compose','primary','restore')}${C.button('翻译 / 恢复未完成段落','translate','secondary','spark')}</div></div>`;
 C.$$('[data-save]',target).forEach(b=>b.onclick=async()=>{const r=rows.find(r=>r.cache_key===b.dataset.save);b.disabled=true;try{await C.api(`/api/papers/${id}/translations/${r.cache_key}`,{method:'PUT',body:{text:C.$(`textarea[data-cache="${r.cache_key}"]`,target).value,updated:r.updated}});R.paper.translated=false;C.toast('本段已保存；重新排版后更新 PDF。');await paintEditor();C.$('#reader-warning').innerHTML='<div class="notice warning">译文已修改，PDF 尚未更新。请使用缓存重新排版。</div>'}catch(e){C.error(e);b.disabled=false}});C.bind(target,{compose:compose,translate:()=>C.translationDialog(id)});
 }
 async function compose(){let spec=R.paper.output?.profile;if(!spec&&R.translationRows?.length)spec=R.translationRows[0].profile;if(!spec){C.toast('没有完整缓存，请先翻译。','error');return}await C.api('/api/papers/'+id+'/compose',{method:'POST',body:{...spec,consent:false}});C.toast('已开始浏览器重新排版，不调用模型。');C.go('/jobs')}
 function setMode(mode){R.mode=mode;C.$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='assistant')paintAssistant();else if(mode==='parallel')paintParallel();else paintEditor().catch(C.error)}
 async function layoutDialog(){const p=R.paper,pg=pageData('source');C.modal('版式检查 · 原文第 '+R.sourcePage+' 页',`<button class="btn secondary" id="reanalyse-layout">浏览器重新识别整篇版式</button><p>自动识别不保证所有版式正确。请对照左侧原文检查：正文顺序、图表边界、公式保护与页眉。数字越小越先翻译。</p><div class="notice">“图形 / 公式”以原 PDF 区域原样保留；“忽略”只用于已核对的页眉等非正文，不能用来掩盖漏页。</div><form id="layout-form"><div class="layout-items">${pg.blocks.map(b=>`<article class="layout-item" data-id="${E(b.id)}"><header><label>顺序<input class="layout-order" type="number" min="0" max="20000" value="${b.order}"></label><label>内容类型<select class="layout-kind"><option value="text" ${b.kind==='text'?'selected':''}>正文翻译</option><option value="protected" ${b.kind==='protected'?'selected':''}>图形 / 公式（保留原样）</option><option value="ignore" ${b.kind==='ignore'?'selected':''}>忽略（非正文）</option></select></label></header><textarea class="layout-text" rows="3" maxlength="15000">${E(b.text)}</textarea><small>${E(b.reason||'依据原始文字与几何位置提取')} · (${b.bbox.map(x=>Math.round(x)).join(', ')})</small></article>`).join('')}</div><label class="check"><input type="checkbox" required>已对照原页核对上述内容；修改会使当前译文 PDF 过期</label><div class="dialog-actions"><button class="btn primary">保存版式修正</button></div></form>`,d=>{C.$('#reanalyse-layout',d).onclick=()=>{d.close();reanalyze()};C.$('#layout-form',d).onsubmit=async e=>{e.preventDefault();const changes=C.$$('.layout-item',d).map(el=>({id:el.dataset.id,kind:C.$('.layout-kind',el).value,text:C.$('.layout-text',el).value,order:+C.$('.layout-order',el).value}));try{await C.api('/api/papers/'+id+'/layout',{method:'PUT',body:{revision:p.revision,changes}});d.close();C.toast('版式已保存；只有原文身份改变的译文缓存才会失效。');C.render()}catch(e){C.error(e)}}})}
 function notesDialog(){C.modal('精读笔记 · '+R.notes.length+' 条',`<div class="form-actions"><a class="btn secondary" href="/api/papers/${id}/notes-export">${I('download')}Markdown</a><a class="btn secondary" href="/api/papers/${id}/annotated">${I('pen')}高亮 / 圈画 PDF</a><a class="btn secondary" href="/api/papers/${id}/project">${I('download')}完整项目备份</a></div><p class="muted">PDF 导出保留高亮与圈画；文字批注、AI 解释和 LaTeX 请用 Markdown 或完整项目备份导出。</p><div class="notes-list">${R.notes.map(n=>`<article class="saved-note"><header><button class="btn text" data-note="${n.id}">第 ${n.page} 页 · 返回原文 ${I('arrow')}</button><button class="icon-btn" data-delete-note="${n.id}" aria-label="删除笔记">${I('trash')}</button></header><blockquote>${E(n.quote||'图形 / 手写批注')}</blockquote>${n.comment?`<p>${E(n.comment)}</p>`:''}${n.latex?C.mathHTML('\\['+n.latex+'\\]'):''}${n.answer?'<details><summary>已保存的 AI 解释</summary>'+C.mathHTML(n.answer)+'</details>':''}<small>${C.time(n.created)}</small></article>`).join('')||'<p class="muted">选中原文并保存后，笔记会显示在这里。</p>'}</div>`,d=>{C.mathEnhance(d);C.$$('[data-note]',d).forEach(b=>b.onclick=async()=>{const n=R.notes.find(n=>n.id===b.dataset.note);d.close();await showPage('source',n.page,false);setSelection(n,{saved:true});R.comment=n.comment;paintAssistant()});C.$$('[data-delete-note]',d).forEach(b=>b.onclick=async()=>{const nid=b.dataset.deleteNote;d.close();if(await C.confirm('删除这条笔记？','删除后不能撤销，原始 PDF 不受影响。')){await C.api(`/api/papers/${id}/notes/${nid}`,{method:'DELETE'});R.notes=R.notes.filter(n=>n.id!==nid);C.$('#notes-count').textContent=R.notes.length;R.paintMarks()}notesDialog()})})}
 async function reanalyze(){
  C.modal('重新识别版式（浏览器处理，不调用 AI）',`<p>使用 PDF.js 重新提取文字层并分组；复杂双栏、公式和图注请人工核对。原件、笔记和旧缓存保留；现有译文标记为旧版。</p><label class="check"><input id="preserve-layout" type="checkbox" checked>保留已人工检查的页面及原有 OCR 文字层</label><p class="muted">完成后重新打开论文，检查正文顺序，再点击“整篇翻译”补齐新识别的段落；不会自动发起计费请求。</p><button class="btn primary" id="start-reanalyse">开始浏览器识别</button>`,d=>{C.$('#start-reanalyse',d).onclick=async e=>{e.currentTarget.disabled=true;try{await C.api('/api/papers/'+id+'/reanalyze',{method:'POST',body:{revision:R.paper.revision,preserve_manual:C.$('#preserve-layout',d).checked}});d.close();C.go('/jobs')}catch(error){C.error(error);e.currentTarget.disabled=false}}});
 }
 function bindTurns(scope){C.$$('[data-turn]',scope).forEach(b=>b.onclick=()=>{const [side,n]=b.dataset.turn.split(':');showPage(side,(side==='source'?R.sourcePage:R.targetPage)+ +n,false)})}
 C.bind(root,{translate:()=>C.translationDialog(id),more:()=>C.paperMenu(id),layout:layoutDialog,reanalyze:reanalyze,notes:notesDialog,compose:compose,focus:()=>document.body.classList.toggle('focus-reading')});
 C.$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));C.$$('[data-mobile]').forEach(b=>b.onclick=()=>{C.$('#reader-split').dataset.mobile=b.dataset.mobile;C.$$('[data-mobile]').forEach(x=>x.classList.toggle('active',x===b))});C.$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));bindTurns(root);C.$('#source-page').onchange=e=>showPage('source',+e.target.value,true);C.$('#source-zoom').onchange=e=>{R.zoom.source=+e.target.value;showPage('source',R.sourcePage,false)};
 R.keys=e=>{if(e.key==='Escape')document.body.classList.remove('focus-reading');if(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();showPage('source',R.sourcePage+(e.key==='ArrowLeft'?-1:1),true)}};window.addEventListener('keydown',R.keys);
 bindScroll('source');setMode(R.mode);await showPage('source',R.sourcePage,false);if(params.get('layout')==='1')layoutDialog();
};
})();
