(() => {
'use strict';const C=ICRF,E=C.escape,I=C.icon;
const featureNames={relevance:'相关性',influence:'本地图影响',recency:'时间新近度',evidence:'原文片段覆盖',bridge:'跨域桥接'};
const fieldNames={title:'标题',keywords:'主题标签',abstract:'文首文字',fulltext:'全文'};
const relationNames={foundation:'基础工作',extends:'方法扩展',validates:'验证支持',contradicts:'质疑 / 矛盾',background:'背景引用'};
const defaults={weights:{relevance:40,influence:30,recency:15,evidence:10,bridge:5},fields:{title:5,keywords:3,abstract:2,fulltext:1},relations:{foundation:1.25,extends:1.1,validates:1,contradicts:1,background:.55},damping:.85,personalization:.4,half_life:5,diversity:.15,limit:30};
function sourceCards(sources){return sources.map((s,i)=>`<a class="source-reference" href="#/reader/${E(s.paperId||s.id)}?page=${s.page}"><span>[${i+1}]</span><div><strong>${E(s.title)}</strong><small>原文第 ${s.page} 页 ${I('arrow')}</small></div></a>`).join('')}
C.searchView=(initial='')=>{
 const root=C.$('#main');root.className='page research-page';const stored=C.read('icrf.v3.search',defaults),prefs={...defaults,...stored,weights:{...defaults.weights,...stored.weights},fields:{...defaults.fields,...stored.fields},relations:{...defaults.relations,...stored.relations}};let active=null,result=null,version=0;
 root.innerHTML=`<header class="page-heading"><div><p class="eyebrow">RESEARCH / 从问题出发</p><h1>让重要的论文，浮现。</h1><p>全文匹配、引用网络与可解释权重一起工作。没有命中，就不会制造结果。</p></div>${C.button('导出本次结果','export','secondary','download')}</header>
 <form class="research-query" id="research-form"><div class="query-input">${I('search')}<input id="research-query" type="search" aria-label="检索论文" maxlength="2000" placeholder="输入问题、关键术语，例如：SRAM 功耗优化" value="${E(initial)}"><button class="btn primary">检索论文 ${I('arrow')}</button></div><div class="search-filters"><label>主题<select id="search-tag"><option value="">所有主题</option>${[...new Set(C.state.papers.flatMap(p=>p.tags))].map(t=>`<option>${E(t)}</option>`).join('')}</select></label><label>起始年份<input type="number" id="year-from" min="1500" max="2200" placeholder="不限"></label><span>—</span><label>结束年份<input type="number" id="year-to" min="1500" max="2200" placeholder="不限"></label><button class="btn text" type="button" id="reset-filters">清除筛选</button></div></form>
 <div class="research-layout"><aside class="ranking-controls"><header><h2>${I('settings')}排序实验室</h2><button class="btn text tiny" id="reset-weights">重置</button></header><p>调整参数后点击检索生效；分数不是论文正确率。</p><label>评分预设<select id="ranking-preset"><option value="custom">自定义</option><option value="balanced">均衡阅读</option><option value="relevant">相关优先</option><option value="influence">引用影响优先</option><option value="recent">新近优先</option></select></label>
 ${Object.entries(featureNames).map(([k,v])=>`<label class="weight-row">${v}<output id="weight-out-${k}">${prefs.weights[k]}</output><input data-weight="${k}" type="range" min="0" max="100" step="1" value="${prefs.weights[k]}" aria-label="${v}权重"></label>`).join('')}
 <p class="field-note">权重自动归一化。全零回退到均衡默认值。</p><details><summary>全文检索字段权重</summary>${Object.entries(fieldNames).map(([k,v])=>`<label class="compact-field">${v}<input data-field="${k}" type="number" min="0" max="100" step=".25" value="${prefs.fields[k]}"></label>`).join('')}<p class="field-note">“文首文字”是前 4000 字符，不冒充已识别的正式摘要。</p></details>
 <label class="check"><input type="checkbox" id="include-candidates" ${prefs.include_candidates?'checked':''}>将待核对引用也纳入排序（默认关闭）</label><details><summary>引用关系权重</summary>${Object.entries(relationNames).map(([k,v])=>`<label class="compact-field">${v}<input data-relation="${k}" type="number" min="0" max="100" step=".05" value="${prefs.relations[k]}"></label>`).join('')}</details>
 <details><summary>PageRank 与多样性参数</summary>${[['damping','阻尼系数',0,.99,.01],['personalization','问题个性化比例',0,1,.05],['half_life','新近度半衰期（年）',.25,50,.25],['diversity','多样性惩罚',0,1,.05],['limit','结果上限',1,200,1]].map(([k,v,min,max,step])=>`<label class="compact-field">${v}<input data-param="${k}" type="number" min="${min}" max="${max}" step="${step}" value="${prefs[k]}"></label>`).join('')}</details><p id="search-dirty" class="notice" hidden>参数已改变，下方仍是上一次结果。</p></aside>
 <section class="search-output"><div id="search-status" aria-live="polite"></div><div id="search-results">${C.empty('下一条线索，从这里开始。','输入一个明确的问题，检索当前工作空间中的真实原文。')}</div></section></div>`;
 function values(){const get=attr=>Object.fromEntries(C.$$('[data-'+attr+']',root).map(e=>[e.dataset[attr],+e.value]));return {include_candidates:C.$('#include-candidates').checked,weights:get('weight'),fields:get('field'),relations:get('relation'),...get('param')}}
 const dirty=()=>{if(result)C.$('#search-dirty').hidden=false};C.$$('input,select',root).forEach(e=>e.addEventListener('input',dirty));C.$$('[data-weight]',root).forEach(e=>e.oninput=()=>{C.$('#weight-out-'+e.dataset.weight).value=e.value;dirty()});
 const presets={balanced:defaults.weights,relevant:{relevance:70,influence:10,recency:5,evidence:10,bridge:5},influence:{relevance:25,influence:55,recency:5,evidence:10,bridge:5},recent:{relevance:35,influence:10,recency:40,evidence:10,bridge:5}};
 C.$('#ranking-preset').onchange=e=>{const v=presets[e.target.value];if(v)for(const[k,n]of Object.entries(v)){C.$('[data-weight="'+k+'"]').value=n;C.$('#weight-out-'+k).value=n}dirty()};C.$('#reset-weights').onclick=()=>{C.write('icrf.v3.search',defaults);C.searchView(C.$('#research-query').value)};
 C.$('#reset-filters').onclick=()=>{C.$('#search-tag').value='';C.$('#year-from').value='';C.$('#year-to').value='';dirty()};
 async function search(e){e?.preventDefault();const query=C.$('#research-query').value.trim();if(!query){C.$('#research-query').focus();return}const args={query,...values(),tag:C.$('#search-tag').value,year_from:C.$('#year-from').value?+C.$('#year-from').value:null,year_to:C.$('#year-to').value?+C.$('#year-to').value:null};C.write('icrf.v3.search',values());active?.abort();active=new AbortController();const seq=++version;C.$('#search-status').innerHTML='<div class="search-running" role="status"><span class="spinner"></span>正在匹配原文与计算本地图排名…<button class="btn secondary" id="stop-search">停止等待</button></div>';C.$('#stop-search').onclick=()=>{active.abort();version++;C.$('#search-status').textContent='已停止等待；上一次结果保留。'};try{const res=await C.api('/api/search',{method:'POST',body:args,signal:active.signal});if(seq!==version||!root.isConnected)return;result={...res,query:args,generatedAt:new Date().toISOString()};C.$('#search-dirty').hidden=true;C.$('#search-status').innerHTML=`<div class="results-heading"><strong>${res.results.length} 篇候选论文</strong><span>${res.diagnostics.candidates||0} 篇参与计算 · ${res.diagnostics.hits||0} 篇全文命中</span></div>`;C.$('#search-results').innerHTML=res.results.length?res.results.map((r,i)=>`<article class="search-result"><div class="result-top"><span class="result-order">${String(i+1).padStart(2,'0')}</span><div><a class="result-title" href="#/reader/${r.id}">${E(r.title)}</a><p class="muted">${r.year||'年份未知'} · ${r.tags.map(E).join(' / ')||'未设置主题'}</p></div><div class="result-score"><strong>${(r.score*100).toFixed(1)}</strong><span>综合分 / 100</span></div></div><div class="feature-bars">${Object.entries(r.features).map(([k,v])=>`<div><span>${featureNames[k]}</span><meter min="0" max="1" value="${v}">${Math.round(v*100)}%</meter><small>${Math.round(v*100)}</small></div>`).join('')}</div>${r.snippets.slice(0,2).map(s=>`<a class="result-excerpt" href="#/reader/${r.id}?page=${s.page}"><span>PDF · 第 ${s.page} 页 ${I('arrow')}</span><p>${E(s.text)}</p></a>`).join('')||'<p class="muted">匹配来自标题或标签，未找到可定位的正文摘录。</p>'}</article>`).join('')+`<details class="diagnostics"><summary>计算诊断与解释</summary><pre>${E(JSON.stringify(res.diagnostics,null,2))}</pre><p>图只描述当前论文库，不等于全球学术影响力。引用候选仍需核验；原文片段覆盖不是证据质量评分。</p></details>`:C.empty('没有找到匹配的论文。','更换关键词或清除年份、主题筛选。不会用无关论文填充结果。');}catch(e){if(seq===version){C.$('#search-status').textContent=e.name==='AbortError'?'检索已停止。':e.message;C.error(e)}}}
 C.$('#research-form').onsubmit=search;C.bind(root,{export:()=>{if(!result){C.toast('请先完成一次检索。');return}C.downloadText('research-results.json',JSON.stringify(result,null,2),'application/json')}});if(initial)search();
};
C.graphView=async()=>{
 const root=C.$('#main');root.className='page graph-page';
 const options=C.state.graphOptions||{candidates:true,rankCandidates:false,similarity:false};C.state.graphOptions=options;
 const ticket=C.state.graphTicket=(C.state.graphTicket||0)+1;
 const data=await C.api(`/api/graph?include_candidates=${options.rankCandidates}&similarity=${options.similarity}`);
 if(C.route().pathname!=='/graph'||ticket!==C.state.graphTicket)return;
 const title=id=>data.nodes.find(n=>n.id===id)?.title||'论文已不存在';
 const visible=data.edges.filter(e=>e.confirmed||options.candidates);
 root.innerHTML=`<header class="page-heading"><div><p class="eyebrow">KNOWLEDGE / 让文献产生连接</p><h1>有证据的连接，才有意义。</h1><p>箭头：引用者 → 被引用者。实线已核对；虚线仅为参考文献候选。主题相似不是引用。</p></div><div class="form-actions">${C.button('添加已核对的关系','add','primary','link')}${C.button('重新扫描引用','refresh','secondary','restore')}${C.button('导出网络','export','secondary','download')}</div></header>
 <div class="graph-layout"><section class="graph-canvas"><div class="graph-toolbar"><span>${data.nodes.length} 篇论文 · ${data.diagnostics.confirmedEdges} 条已确认 · ${data.diagnostics.candidateEdges} 条候选</span><div><button class="icon-btn" id="graph-minus" aria-label="缩小关系图">−</button><button class="icon-btn" id="graph-plus" aria-label="放大关系图">＋</button><button class="btn text" id="graph-reset">复位</button></div></div>
 <div class="graph-filters"><label class="check"><input id="show-candidates" type="checkbox" ${options.candidates?'checked':''}>显示引用候选</label><label class="check"><input id="rank-candidates" type="checkbox" ${options.rankCandidates?'checked':''}>候选参与 PageRank</label><label class="check"><input id="show-similarity" type="checkbox" ${options.similarity?'checked':''}>显示主题相似线（不参与排名）</label></div>
 <div id="graph-space"></div><div class="graph-legend"><span><i></i>已核对引用</span><span><i class="dashed"></i>DOI / 完整标题候选</span><span><i class="dotted"></i>主题相似</span><small>拖动平移 · 点击节点精读 · 点击线查看证据</small></div></section>
 <aside class="graph-inspector"><h2>关系与证据</h2><p>仅扫描本地论文的参考文献，不联网，不调用模型；同主题论文不一定互相引用。</p><div id="edge-list">${visible.map(e=>`<article class="edge-card"><span class="tag ${e.confirmed?'green':'amber'}">${e.confirmed?'已人工核对':E(e.evidenceLabel||'待核对')}</span><p>${E(title(e.source))}<strong>↓ ${relationNames[e.relation]||'背景引用'}</strong>${E(title(e.target))}</p>${e.evidence?`<p class="edge-evidence">${E(e.evidence)}</p><a class="btn text tiny" href="#/reader/${e.source}?page=${e.page}">查看来源第 ${e.page} 页 ${I('arrow')}</a>`:''}<button class="btn text" data-edge="${data.edges.indexOf(e)}">${e.confirmed?'编辑 / 撤销确认':'核对并确认'}</button><button class="btn text" data-exclude="${data.edges.indexOf(e)}">排除此关系</button></article>`).join('')||'<p class="notice">没有显示的引用关系。可能没有互引、参考文献未被识别，或候选层被关闭。可以核对论文元数据与参考文献；不会制造连线。</p>'}</div>
 ${data.excluded?.length?`<details><summary>已排除 ${data.excluded.length} 条关系</summary>${data.excluded.map((e,i)=>`<p>${E(title(e.source))} → ${E(title(e.target))}<button class="btn text tiny" data-restore-edge="${i}">恢复自动发现</button></p>`).join('')}</details>`:''}
 <details><summary>算法诊断与作用范围</summary><pre>${E(JSON.stringify({...data.diagnostics,ranks:undefined},null,2))}</pre><p>自动候选只标记为背景引用，不推断“支持/反对”结论。PageRank 不代表正确率或全球影响力。</p></details></aside></div>`;
 function edgeDialog(edge={}){
  if(data.nodes.length<2){C.toast('至少需要两篇论文才能建立关系。');return;}
  const select=id=>data.nodes.map(n=>`<option value="${n.id}" ${n.id===id?'selected':''}>${E(n.title.slice(0,120))}</option>`).join('');
  C.modal('核对引用证据与方向',`<form id="edge-form">${edge.evidence?`<p class="edge-evidence">${E(edge.evidence)}</p><a href="#/reader/${edge.source}?page=${edge.page}" id="check-edge-source" class="btn text">先查看来源第 ${edge.page} 页</a>`:''}<label>引用者<select id="edge-source">${select(edge.source)}</select></label><label>被引用者<select id="edge-target">${select(edge.target||data.nodes[1]?.id)}</select></label><label>关系类型<select id="edge-type">${Object.entries(relationNames).map(([k,v])=>`<option value="${k}" ${k===(edge.relation||'background')?'selected':''}>${v}</option>`).join('')}</select></label><label class="check"><input type="checkbox" required>我已查看原文，确认引用方向和关系含义</label><div class="dialog-actions">${edge.confirmed?'<button type="button" class="btn danger" id="delete-edge">撤销人工确认</button>':''}<button class="btn primary">保存已核对关系</button></div></form>`,d=>{
   if(C.$('#check-edge-source',d))C.$('#check-edge-source',d).onclick=()=>d.close();
   C.$('form',d).onsubmit=async event=>{event.preventDefault();try{await C.api('/api/graph/edges',{method:'POST',body:{source:C.$('#edge-source',d).value,target:C.$('#edge-target',d).value,relation:C.$('#edge-type',d).value}});d.close();C.graphView().catch(C.error)}catch(error){C.error(error)}};
   if(C.$('#delete-edge',d))C.$('#delete-edge',d).onclick=async()=>{try{await C.api(`/api/graph/edges?source=${edge.source}&target=${edge.target}`,{method:'DELETE'});d.close();C.graphView().catch(C.error)}catch(error){C.error(error)}};
  });
 }
 const nodes=data.nodes.slice(0,200),nodeIds=new Set(nodes.map(n=>n.id));
 const shown=[...visible,...(data.similarities||[])].filter(e=>nodeIds.has(e.source)&&nodeIds.has(e.target));
 if(nodes.length){
  // A small graph is arranged horizontally. Larger ones use concentric rings
  // rather than the old two-node vertical gap occupying the whole viewport.
  const positions=new Map(nodes.map((n,i)=>{
   if(nodes.length===1)return[n.id,{x:450,y:285}];
   if(nodes.length===2)return[n.id,{x:260+i*380,y:285}];
   const ring=Math.floor(i/18),inRing=Math.min(18,nodes.length-ring*18),angle=2*Math.PI*(i%18)/inRing-Math.PI/2;
   return[n.id,{x:450+Math.cos(angle)*(220+ring*95),y:300+Math.sin(angle)*(180+ring*80)}];
  }));
  const max=Math.max(...Object.values(data.diagnostics.ranks),.001),radius=n=>18+18*(data.diagnostics.ranks[n]||0)/max;
  const xs=[...positions.values()].map(p=>p.x),ys=[...positions.values()].map(p=>p.y),xMin=Math.min(0,...xs.map(x=>x-150)),yMin=Math.min(0,...ys.map(y=>y-80)),vw=Math.max(900,...xs.map(x=>x+150))-xMin,vh=Math.max(600,...ys.map(y=>y+90))-yMin;
  C.$('#graph-space').innerHTML=`${data.nodes.length>200?'<p class="notice">为保持可读性，当前图显示前 200 篇；导出的 JSON 和右侧关系仍包含全库。</p>':''}<svg id="network-svg" viewBox="${xMin} ${yMin} ${vw} ${vh}" role="img" aria-label="有向引用网络"><defs><marker id="edge-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0 L10 5 L0 10Z" fill="#67896f"/></marker></defs><g id="graph-transform">${shown.map((e,i)=>{const a=positions.get(e.source),b=positions.get(e.target),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,ar=radius(e.source)+2,br=radius(e.target)+5,similar=e.relation==='similarity',reverse=shown.some(other=>other.source===e.target&&other.target===e.source),bend=reverse&&!similar?35:0;const d=`M${a.x+dx/len*ar},${a.y+dy/len*ar} Q${(a.x+b.x)/2-dy/len*bend},${(a.y+b.y)/2+dx/len*bend} ${b.x-dx/len*br},${b.y-dy/len*br}`;return `<path d="${d}" class="graph-edge ${similar?'similarity':e.confirmed?'':'candidate'}" ${similar?'':'marker-end="url(#edge-arrow)"'}/><path d="${d}" class="graph-edge-hit" data-line="${i}" tabindex="0" role="button" aria-label="${E(title(e.source))} ${similar?'与':'引用'} ${E(title(e.target))}"><title>${E(similar?'主题相似，不是引用':e.evidenceLabel||'人工确认引用')}</title></path>`}).join('')}${nodes.map((n,i)=>{const p=positions.get(n.id),r=radius(n.id);return `<a href="#/reader/${n.id}" class="graph-node" aria-label="精读 ${E(n.title)}"><circle cx="${p.x}" cy="${p.y}" r="${r}"/><text x="${p.x}" y="${p.y+4}" text-anchor="middle">${String(i+1).padStart(2,'0')}</text><text class="graph-label" x="${p.x}" y="${p.y+r+22}" text-anchor="middle">${E(n.title.length>32?n.title.slice(0,30)+'…':n.title)}</text><title>${E(n.title)}</title></a>`}).join('')}</g></svg>`;
  let zoom=1,dx=0,dy=0;
  const paint=()=>C.$('#graph-transform').setAttribute('transform',`translate(${(xMin+vw/2)*(1-zoom)+dx},${(yMin+vh/2)*(1-zoom)+dy}) scale(${zoom})`),svg=C.$('#network-svg');
  C.$('#graph-plus').onclick=()=>{zoom=C.clamp(zoom*1.2,.4,4);paint()};C.$('#graph-minus').onclick=()=>{zoom=C.clamp(zoom/1.2,.4,4);paint()};C.$('#graph-reset').onclick=()=>{zoom=1;dx=dy=0;paint()};
  svg.onpointerdown=e=>{if(e.target.closest('a,[data-line]'))return;svg.setPointerCapture(e.pointerId);const x=e.clientX,y=e.clientY,px=dx,py=dy;svg.onpointermove=event=>{const scale=vw/svg.getBoundingClientRect().width;dx=px+(event.clientX-x)*scale;dy=py+(event.clientY-y)*scale;paint()};svg.onpointerup=svg.onpointercancel=()=>svg.onpointermove=null};
  C.$$('[data-line]').forEach(el=>{const open=()=>{const e=shown[+el.dataset.line];if(e.relation==='similarity')C.modal('主题相似，不是引用',`<p>共同术语：${e.sharedTerms.map(E).join('、')}</p><p>标题/标签 Jaccard 相似度：${e.score.toFixed(2)}。这条线不计入 PageRank。</p>`);else edgeDialog(e)};el.onclick=open;el.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}}});
 }else C.$('#graph-space').innerHTML=C.empty('还没有可以连接的论文。','导入论文后，从原文参考文献建立证据链。',C.button('导入论文','import','primary','upload'));
 C.$$('[data-edge]').forEach(b=>b.onclick=()=>edgeDialog(data.edges[+b.dataset.edge]));
 C.$$('[data-exclude]').forEach(b=>b.onclick=async()=>{const e=data.edges[+b.dataset.exclude];if(!await C.confirm('排除此关系？','只隐藏此关系，不删除论文；之后可以恢复自动发现。'))return;try{await C.api('/api/graph/exclusions',{method:'POST',body:{source:e.source,target:e.target}});C.graphView().catch(C.error)}catch(error){C.error(error)}});
 C.$$('[data-restore-edge]').forEach(b=>b.onclick=async()=>{const e=data.excluded[+b.dataset.restoreEdge];try{await C.api(`/api/graph/edges?source=${e.source}&target=${e.target}`,{method:'DELETE'});C.graphView().catch(C.error)}catch(error){C.error(error)}});
 for(const [id,key] of [['show-candidates','candidates'],['rank-candidates','rankCandidates'],['show-similarity','similarity']])C.$('#'+id).onchange=e=>{options[key]=e.target.checked;C.graphView().catch(C.error)};
 C.bind(root,{add:()=>edgeDialog(),refresh:()=>C.graphView(),export:()=>C.downloadText('citation-network.json',JSON.stringify(data,null,2),'application/json'),import:C.importDialog});
};
C.chatView=()=>{
 const root=C.$('#main');root.className='page chat-page';let mode='local',busy=false,abort=null,seq=0,consent=false,profile=C.profile();
 root.innerHTML=`<header class="page-heading"><div><p class="eyebrow">ASK / 证据在前，理解在后</p><h1>和论文对话。也可以，只聊问题。</h1><p>三种模式彼此隔离；普通对话不会读取你的论文库。</p></div></header><section class="chat-workspace"><div class="chat-mode-bar segmented"><button data-chat-mode="local" class="active">${I('search')}本地证据 · 不联网</button><button data-chat-mode="evidence">${I('book')}论文问答</button><button data-chat-mode="normal">${I('chat')}普通对话</button></div><div id="chat-scope" class="chat-scope"></div><div id="chat-history" class="chat-history" aria-live="polite"></div><form id="chat-form"><label class="check" id="chat-consent-wrap" hidden><input type="checkbox" id="chat-consent">同意将本次内容发送到 ${E(profile.base_url)} / ${E(profile.model||'尚未配置模型')}，可能产生费用</label><div class="chat-composer"><textarea id="chat-question" maxlength="4000" rows="2" aria-label="输入问题" placeholder="输入一个具体问题…" required></textarea><button class="btn primary" id="send-chat">${I('arrow')}发送</button><button class="btn secondary" id="stop-chat" type="button" hidden>${I('stop')}停止</button></div><footer><span id="chat-footnote"></span><button type="button" class="btn text tiny" id="clear-chat">清空本模式对话</button></footer></form></section>`;
 function paint(){C.$('#chat-scope').textContent=mode==='local'?'仅检索当前工作空间，展示原文页码与片段。不调用 AI。':mode==='evidence'?'每次问题独立检索真实摘录；无证据时不调用模型。请写全术语，不使用“上一篇”等跨轮指代。':'普通对话：仅发送本模式最近对话和当前问题，不读取任何论文。';C.$('#chat-consent-wrap').hidden=mode==='local';C.$('#chat-consent').checked=consent;C.$('#chat-footnote').textContent=mode==='local'?'本地检索 · 零模型费用':'AI 生成不保证正确；停止浏览器等待不保证撤销计费。';const messages=C.state.chat[mode];C.$('#chat-history').innerHTML=messages.length?messages.map(m=>`<article class="chat-message ${m.role}"><div class="message-avatar">${I(m.role==='user'?'chat':mode==='local'?'search':'spark')}</div><div><strong>${m.role==='user'?'你':m.role==='error'?'请求未完成（非 AI 回答）':mode==='local'?'本地原文':'科研助手'}</strong>${C.mathHTML(m.content)}${m.sources?'<div class="source-references">'+sourceCards(m.sources)+'</div>':''}${m.warning?'<p class="notice warning">'+E(m.warning)+'</p>':''}</div></article>`).join(''):`<div class="chat-welcome">${I('spark')}<h2>${mode==='local'?'先找到证据，再形成判断。':mode==='normal'?'把复杂问题，拆开聊。':'让回答，始终有出处。'}</h2><p>可以问：“这些论文如何评估 SRAM 的能耗？”</p></div>`;C.mathEnhance(C.$('#chat-history'));if(busy)C.$('#chat-history').insertAdjacentHTML('beforeend','<div class="chat-wait" role="status"><span class="spinner"></span>正在处理当前问题…</div>');C.$('#send-chat').disabled=busy;C.$('#stop-chat').hidden=!busy;C.$('#chat-history').scrollTop=C.$('#chat-history').scrollHeight;}
 C.$$('[data-chat-mode]').forEach(b=>b.onclick=()=>{seq++;abort?.abort();busy=false;consent=false;mode=b.dataset.chatMode;C.$$('[data-chat-mode]').forEach(x=>x.classList.toggle('active',x===b));paint()});C.$('#chat-consent').onchange=e=>{consent=e.target.checked;if(!consent&&busy){seq++;abort?.abort();busy=false;paint()}};C.$('#stop-chat').onclick=()=>{seq++;abort?.abort();busy=false;paint();C.toast('已停止等待。')};C.$('#clear-chat').onclick=()=>{seq++;abort?.abort();busy=false;C.state.chat[mode]=[];paint()};
 C.$('#chat-form').onsubmit=async e=>{e.preventDefault();const question=C.$('#chat-question').value.trim();if(!question||busy)return;if(mode!=='local'&&!consent){C.toast('请先确认外发范围和模型费用。','error');return}if(mode!=='local'){try{C.validateProfile(profile)}catch(err){C.error(err);return}}const current=mode,version=++seq;abort=new AbortController();const history=C.state.chat[current].filter(x=>['user','assistant'].includes(x.role)&&!x.failed).slice(-10).map(({role,content})=>({role,content}));const questionMessage={role:'user',content:question};C.state.chat[current].push(questionMessage);C.$('#chat-question').value='';busy=true;paint();try{let out;if(current==='local'){const r=await C.api('/api/search',{method:'POST',body:{query:question,limit:6},signal:abort.signal});const sources=r.results.flatMap(p=>p.snippets.slice(0,2).map(s=>({...s,paperId:p.id,title:p.title}))).slice(0,8);out={text:sources.length?sources.map((s,i)=>`[${i+1}] 第 ${s.page} 页：${s.text}`).join('\n\n'):'没有找到相关原文。可以换用论文里的英文术语或更具体的关键词。',sources};}else out=await C.api('/api/chat',{method:'POST',signal:abort.signal,body:{profile,mode:current,question,history:current==='normal'?history:[],consent:true}});if(version!==seq||!root.isConnected)return;C.state.chat[current].push({role:'assistant',content:out.text,sources:out.sources,warning:out.invalidCitations?.length?'回复包含不存在的来源编号，请勿直接引用。':out.localOnly?'本次没有找到证据，也没有调用模型。':null});busy=false;paint()}catch(e){if(version===seq){busy=false;questionMessage.failed=true;C.state.chat[current].push({role:'error',content:e.name==='AbortError'?'已停止等待。':'本次请求未完成：'+C.errorText(e)});if(!C.$('#chat-question').value)C.$('#chat-question').value=question;paint();C.error(e)}}};
 const teardown=()=>{seq++;abort?.abort();window.removeEventListener('hashchange',teardown)};window.addEventListener('hashchange',teardown);paint();
};
})();
